
export const RECEIVED_BLINDS_SUCCESSFUL = 'RECEIVED_BLINDS_SUCCESSFUL';
export const RECEIVED_BLINDS_FAILED = 'RECEIVED_BLINDS_FAILED';

export const OPENED_BLIND_SUCCESSFUL = 'OPENED_BLIND_SUCCESSFUL';
export const OPENED_BLIND_FAILED = 'OPENED_BLIND_FAILED';

export const CLOSED_BLIND_SUCCESSFUL = 'CLOSED_BLIND_SUCCESSFUL';
export const CLOSED_BLIND_FAILED = 'CLOSED_BLIND_FAILED';

export const GET_BLIND_SUCCESSFUL = 'GET_BLIND_SUCCESSFUL';
export const GET_BLIND_FAILED = 'GET_BLIND_FAILED';


//  USER

export const LOGIN_ATTEMPTED = 'LOGIN_ATTEMPTED';
export const LOGIN_SUCCESSFUL = 'LOGIN_SUCCESSFUL';
export const LOGIN_FAILED = 'LOGIN_FAILED';