
export const RECEIVED_BLINDS_SUCCESSFUL = 'RECEIVED_BLINDS_SUCCESSFUL';
export const RECEIVED_BLINDS_FAILED = 'RECEIVED_BLINDS_FAILED';

export const OPENED_BLIND_SUCCESSFUL = 'OPENED_BLIND_SUCCESSFUL';
export const OPENED_BLIND_FAILED = 'OPENED_BLIND_FAILED';

